name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore APT cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt
      
      - name: Restore cached SPM dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: swiftpm-${{ runner.os }}-${{ inputs.swift-version }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            swiftpm-${{ runner.os }}-${{ inputs.swift-version }}-
            swiftpm-${{ runner.os }}-

      - name: Install dependencies
        run: |
          apt update
          apt-get install -y libsdl2-dev
          sdl2-config --version

      - name: Build Release
        run: swift build -c release

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-artifacts-linux-${{ matrix.swift }}-${{ github.run_id }}
          path: |
            .build/*.yaml
            .build/*.xml
            .build/*.json
            .build/*.txt
            .build/**/*.json
            .build/**/*.txt
            .build/**/*.a
            .build/**/*.dSYM
            .build/**/*.gdb
            .build/**/*.bundle
            .build/**/Asteroids
            .build/**/Particles
          if-no-files-found: warn
          include-hidden-files: true
